/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32l4_gpio_driver.h"

#define GPIOAEN   (1U << 0)
#define PIN5      (1U<<5)
#define LED_PIN   PIN5

int main(void)
{
    // 1. Enable GPIOA clock
    RCC->AHB2ENR |= GPIOAEN;

    // 2. Set PA5 as output
    GPIOA->MODER |= (1U << 10);
    GPIOA->MODER &= ~(1U << 11);

    while(1)
    {
        // Toggle LED
        GPIO_TogglePin(GPIOA, LED_PIN);

        // Delay
        for(int i = 0; i < 1000000; i++);
    }
}
